name: Staging release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ui-release:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production # Next.js allows development, test, production - no staging!

    permissions: # required by google-github-actions/auth
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - run: ls
      - run: yarn --frozen-lockfile --production=false # we need dev dependencies for building
      - run: yarn run build

      - uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/939144647133/locations/global/workloadIdentityPools/github/providers/my-repo'
          service_account: '881657211299-compute@developer.gserviceaccount.com'

      # upload files to GCS
      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'out'
          destination: 'cs-2060-hw-6'
          parent: false

