name: Deploy to Google Cloud Storage

on:
  push:
    branches:
    - main  

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment.

  steps:
  - name: Checkout Repo
    uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
  - name: Authenticate to Google Cloud- name: Authenticate to Google Cloud    
    uses: google-github-actions/auth@v2  # Authenticates to Google Cloud with the Workload Identity Federation.
    with:
      project_id: 'sylvan-client-411600'  # Your Google Cloud project ID.
      workload_identity_provider: 'projects/939144647133/locations/global/workloadIdentityPools/github/providers/my-repo'

  - name: Upload to Google Cloud Storage
    run: |
      gsutil cp ./static-site/. gs:///
